
import { Position } from 'reactflow';
import { CustomNodeLayout } from './node-templates';

export const defaultTemplates: CustomNodeLayout[] = [
  {
    name: 'Carte de Profil Simple',
    width: 250,
    height: 100,
    elements: [
      {
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 250,
        height: 100,
        fill: '#ffffff',
        stroke: '#dee2e6',
        strokeWidth: 1,
        borderRadius: { tl: 8, tr: 8, br: 8, bl: 8 },
      },
      {
        type: 'image',
        x: 20,
        y: 20,
        width: 60,
        height: 60,
        dataKey: 'avatar',
        src: '{{data.avatar}}',
        borderRadius: { tl: 30, tr: 30, br: 30, bl: 30 },
      },
      {
        type: 'text',
        x: 95,
        y: 35,
        width: 135,
        height: 20,
        dataKey: 'name',
        content: '{{data.name}}',
        fill: '#212529',
        fontSize: 16,
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
      },
      {
        type: 'text',
        x: 95,
        y: 60,
        width: 135,
        height: 20,
        dataKey: 'poste',
        content: '{{data.poste}}',
        fill: '#6c757d',
        fontSize: 14,
        fontFamily: 'sans-serif',
      },
    ],
    handles: [
      { id: 'top-target', type: 'handle', handleType: 'target', position: Position.Top, x: 125, y: 0 },
      { id: 'bottom-source', type: 'handle', handleType: 'source', position: Position.Bottom, x: 125, y: 100 },
      { id: 'left-target', type: 'handle', handleType: 'target', position: Position.Left, x: 0, y: 50 },
      { id: 'left-source', type: 'handle', handleType: 'source', position: Position.Left, x: 0, y: 50 },
      { id: 'right-target', type: 'handle', handleType: 'target', position: Position.Right, x: 250, y: 50 },
      { id: 'right-source', type: 'handle', handleType: 'source', position: Position.Right, x: 250, y: 50 },
    ],
  },
  {
    name: 'Carte Article',
    width: 300,
    height: 120,
    elements: [
      {
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 300,
        height: 120,
        fill: '#f8f9fa',
        stroke: '#ced4da',
        strokeWidth: 1,
        borderRadius: { tl: 6, tr: 6, br: 6, bl: 6 },
      },
      {
        type: 'text',
        x: 15,
        y: 25,
        width: 270,
        height: 24,
        dataKey: 'title',
        content: '{{data.title}}',
        fill: '#000000',
        fontSize: 18,
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
      },
      {
        type: 'line',
        x1: 15,
        y1: 50,
        x2: 285,
        y2: 50,
        stroke: '#e9ecef',
        strokeWidth: 2,
      },
      {
        type: 'text',
        x: 15,
        y: 80,
        width: 270,
        height: 40,
        dataKey: 'description',
        content: '{{data.description}}',
        fill: '#495057',
        fontSize: 14,
        fontFamily: 'sans-serif',
      },
    ],
    handles: [
      { id: 'top-target', type: 'handle', handleType: 'target', position: Position.Top, x: 150, y: 0 },
      { id: 'bottom-source', type: 'handle', handleType: 'source', position: Position.Bottom, x: 150, y: 120 },
      { id: 'left-target', type: 'handle', handleType: 'target', position: Position.Left, x: 0, y: 60 },
      { id: 'left-source', type: 'handle', handleType: 'source', position: Position.Left, x: 0, y: 60 },
      { id: 'right-target', type: 'handle', handleType: 'target', position: Position.Right, x: 300, y: 60 },
      { id: 'right-source', type: 'handle', handleType: 'source', position: Position.Right, x: 300, y: 60 },
    ],
  },
];
